# coding=utf-8
#
# Copyright 2024
# Heinrich Heine University Dusseldorf,
# Faculty of Mathematics and Natural Sciences,
# Computer Science Department
#
# Authors:
# Renato Vukovic (renato.vukovic@hhu.de)
#
# This code was generated with the help of AI writing assistants
# including GitHub Copilot, ChatGPT, Bing Chat.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
from dataclasses import dataclass, asdict


@dataclass
class chatgpt_sql_prediction_config():
	model_name: str  # name of the model
	dataset: str  # name of the dataset
	splits: list[str]  # list of splits to be used for the prediction
	max_tokens: int = 4096  # maximum number of new tokens to be generated by the model
	prompt_name: str = "zeroshot_default"  # prompt for the model
	use_concept_matching: bool = False  # whether to use concept matching
	batch_size: int = 1  # number of articles to put in the query at once
	return_column_values: bool = False  # whether to return all possible values for a column
	seed: int = None #seed for the random order of the dialogues how they are presented to the model during inference


	#method for returning the config params as a dict for saving as json
	def to_dict(self):
		return asdict(self)
		